cluster:
  zookeeper:
    hostPort: {ZK_ADDRESSES}
    sessionTimeout: 100000
agent_server:
  jetty:
    host: {BIND_HOST}
    port: {AGENT_SERVER_BIND_PORT}
    context_path: /
agent_stream:
  grpc:
    host: {BIND_HOST}
    port: {GRPC_BIND_PORT}
  jetty:
    host: {UI_BIND_HOST}
    port: {UI_BIND_PORT}
    context_path: /
ui:
  jetty:
    host: {UI_BIND_HOST}
    port: {UI_BIND_PORT}
    context_path: /
collector_inside:
  grpc:
    host: {CLUSTER_BIND_HOST}
    port: {CLUSTER_BIND_PORT}
storage:
  elasticsearch:
    cluster_name: {ES_CLUSTER_NAME}
    cluster_transport_sniffer: true
    cluster_nodes: {ES_ADDRESSES}
    index_shards_number: 2
    index_replicas_number: 0
