cluster:
  zookeeper:
    hostPort: localhost:2181
    sessionTimeout: 100000
#  redis:
#    host: localhost
#    port: 6379
queue:
  disruptor: on
  data_carrier: off
agentstream:
  grpc:
    host: localhost
    port: 1000
  jetty:
    host: localhost
    port: 2000
    context_path: /
discovery:
  grpc: localhost
  port: 1000
ui:
  jetty:
    host: localhost
    port: 12800

